#!/bin/bash

function airplane {
    # Modification de grub pour le mode avion (modification de toute la ligne qui commence par: GRUB_CMDLINE_LINUX_DEFAULT)
    sed -i '/^GRUB_CMDLINE_LINUX_DEFAULT/c\GRUB_CMDLINE_LINUX_DEFAULT="quiet splash acpi_os_name=Linux acpi_osi= "' /etc/default/grub 
}

function nvidia {
    # Installation du pilote Nvidia
    echo -e ${CYAN}"Installation du pilote Nvidia"${RESETCOLOR}
    add-apt-repository -y ppa:graphics-drivers/ppa
    apt update
    apt install nvidia-390
}

function tuxedoAirplane {
    # Installation airplane driver Tuxedo pour la P775DM3
    echo -e ${CYAN}"Installation du module Tuxedo"${RESETCOLOR}
#TODO
}

function languages {
    # Message pour ne pas oublier de finir la configuration du système
    echo -e ${PINK}"\n\n!! Ne pas oublier de mettre a jour la langue du système !!"${RESETCOLOR}
}
